version: '3.8'
name: draw123
services:
  api:
    container_name: draw123_api
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    command: npm run start:dev
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
  db:
    container_name: draw123_db
    image: postgres:14.1
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
